version: '3.7'

services:
    vaultwarden:
        image: vaultwarden/server:latest
        container_name: vaultwarden
        restart: always
        networks:
          - traefik
        volumes:
          - ./data:/data
        environment:
          SIGNUPS_ALLOWED: false # set to false to disable signups
          WEBSOCKET_ENABLED: true
          ADMIN_TOKEN: "${vault_admin}"
        labels: 
          traefik.enable: true
          traefik.http.routers.vaultwarden.rule: Host(`vaultwarden.swiles.tech`)
          traefik.http.routers.vaultwarden.entrypoints: https
          traefik.http.services.vaultwarden.loadbalancer.server.port: 80
networks:
    traefik:
      external: true
