version: '3.7'

services:
    zipline:
        image: ghcr.io/diced/zipline
        container_name: zipline
        restart: always
        environment:
          - CORE_RETURN_HTTPS=false
          - CORE_SECRET="${zipline_secret}"
          - CORE_HOST=0.0.0.0
          - CORE_PORT=3000
          - CORE_DATABASE_URL="${zipline_db}"
          - CORE_LOGGER=true
          - WEBSITE_TITLE=Swiles Uploads
          - WEBSITE_SHOW_VERSION=true
        networks:
          - traefik
          - database
        volumes:
          - './.uploads:/zipline/uploads'
          - './.public:/zipline/public'
        labels: 
          traefik.enable: true
          traefik.http.routers.zipline.rule: Host(`upload.swiles.tech`)
          traefik.http.routers.zipline.entrypoints: https
          traefik.http.services.zipline.loadbalancer.server.port: 3000
networks:
    traefik:
      external: true
    database:
      external: true