global:
    checkNewVersion: true
    sendAnonymousUsage: true

log:
    level: debug

metrics:
    prometheus:
        buckets:
            - 0.1
            - 0.3
            - 1.2
            - 5.0
        addEntryPointsLabels: true
        addServicesLabels: true

entryPoints:
    http:
        address: ':80'
        http:   
            redirections:
                entryPoint:
                    to: https
                    permanent: true
    https:
        address: ':443'
        http:
            tls:
                certResolver: default
                domains:
                    - main: 'swiles.tech'
                      sans:
                        - howtowhipandnaenae.ninja 
                        - swiles.tech
                        - traefik.swiles.tech
                        - uptime.swiles.tech
                        - geoguessrapi.swiles.tech
                        - geoguessr.swiles.tech
                        - vaultwarden.swiles.tech
providers:
    docker:
        exposedByDefault: false
        network: traefik

    file:
        directory: '/configs'


api:
    dashboard: true

certificatesResolvers:
    default:
        acme:
            #caserver: https://acme-staging-v02.api.letsencrypt.org/directory
            email: daily@swiles.tech
            storage: /letsencrypt/acme.json
            httpChallenge:
                entryPoint: http

