version: '3.7'

services:
    database-zip:
        image: postgres:14.0
        container_name: database-zip
        restart: unless-stopped
        env_file:
            - enviroment.env
        volumes:
            - ./.data/postgres/:/var/lib/postgresql/data/
        networks:
            - database
            - pgadmin
    pgadmin:
        image: dpage/pgadmin4:latest
        container_name: pgadmin
        restart: unless-stopped
        env_file:
            -  enviroment.env
        volumes:
            - ./.data/pgadmin:/var/lib/pgadmin
        networks:
            - pgadmin
            - database
            - traefik
        labels:
            traefik.enable: true
            traefik.http.routers.pgadmin.rule: Host(`database.swiles.tech`)
            traefik.http.routers.pgadmin.entrypoints: https
            traefik.http.services.pgadmin.loadbalancer.server.port: 80

networks:
    database:
        name: database
    pgadmin:
        name: pgadmin
    traefik:
        external: true