version: '3.7'

services: 
  database-workout:
      image: postgres:14.0
      container_name: database-workout
      restart: unless-stopped
      env_file:
        - enviroment.env
      volumes:
        - ./.data/postgres/:/var/lib/postgresql/data/
      networks:
        - database
      ports:
        - 5432:5432
networks:
  database:
    external: true
  pgadmin:
    external: true
  