version: '3.7'
services:
  geo_website:
    image: ghcr.io/shanew-18/geoguessr-ai/web:master
    container_name: geo_web
    restart: always
    networks:
      - traefik
    labels:
      traefik.enable: true
      traefik.http.routers.geo_website.rule: Host(`geoguessr.swiles.tech`)
      traefik.http.routers.geo_website.entrypoints: https
      traefik.http.services.geo_website.loadbalancer.server.port: 3000

networks:
  traefik:
    external: true
